install.packages("tidyverse")
install.packages("rmarkdown")
install.packages("httr")
install.packages("shiny")
install.packages("shinydashboard")
install.packages("shinythemes")
install.packages("stringr")
install.packages("leaflet")
install.packages("ggExtra")

if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("EBImage")
