install.packages("tidyverse")
install.packages("rmarkdown")
install.packages("httr")
install.packages("shiny")
install.packages("shinydashboard")
install.packages("stringr")
install.packages('leaflet')
install.packages("ggExtra")
